# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-07 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20181123_0233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Term',
            new_name='Query',
        ),
    ]
